### ISSUE TITLE
Asking for Authorization with Windows Phone SDK

### ISSUE THREAD

**Issue by Bruno125** [paypal/Windows8SDK#30]
Hello. My team had integrated Paypal on both Android and iOS platform, and had no problems. We need to get just the authorization (for example, in iOS we do: payment.intent = PaypalPaymentIntentAuthorize, or set PaypalPayment.PAYMENT_INTENT_AUTHORIZE in Android). Is there any way to do this with the windows phone sdk? I can't seem to find a way to do that.

While granting permissions, I tried selecting "Use Express Checkout to process payments." and "Use Express Checkout to process mobile payments." (as the guide describes, but this completes the transaction, doesn't give me just the authorization). Then I tried with "Authorize and capture your PayPal transactions." and "Obtain authorization for pre-approved payments and initiate pre-approved transactions." but neither of them seem to work.
 Thanks in advance.

**Comment by jziaja** [comment]
Hi @Bruno125 , unfortunately, getting just the authorization using this SDK isn't currently possible.  This SDK was created a couple years ago with a single purpose of allowing for a simple 'Buy Now' feature using the legacy Classic API that creates a one-time sale payment.

I should note that we are considering updating this SDK with support for calling the REST APIs.  If we do provide this update, I'll see if we can include expanding the payment support to more than just the single sale transaction case.
